[App]
Mode = "debug"

[Http]
Static = "./dist"
Https = false
HttpsCert = ""
HttpKey = ""
Port = 8088

[Log]
Level = "debug"

[Database]

[Database.MySQL]
Host = "localhost"
Port = 3306
Database = "demos"
Username = "root"
Password = "root"
